=== streamr-dev/network/packages/broker/src/helpers/config.schema.json
{
    "$id": "config.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Broker configuration format",
    "type": "object",
    "required": [
        "client",
        "plugins"
    ],
    "additionalProperties": false,
    "properties": {
        "client": {
            "type": "object",
            "description": "Client configuration",
            "additionalProperties": true,
            "properties": {
                "auth": {
                    "type": "object",
                    "properties": {
                        "privateKey": {
                            "type": "string",
                            "pattern": "^(0x)?[a-fA-F0-9]{64}$"
                        }
                    },
                    "required": ["privateKey"]
                }
            },
            "required": ["auth"]
        },
        "plugins": {
            "type": "object",
            "description": "Plugin configurations",
            "additionalProperties": true
        },
        "httpServer": {
            "type": [
                "object"
            ],
            "description": "HTTP server configuration",
            "default": {},
            "additionalProperties": false,
            "properties": {
                "port": {
                    "$ref": "#/definitions/port",
                    "description": "Port to start HTTP server on",
                    "default": 7171
                },
                "certFileName": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "description": "Path of certificate file to use for SSL",
                    "default": null
                },
                "privateKeyFileName": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "description": "Path of private key file to use for SSL",
                    "default": null
                }
            }
        },
        "apiAuthentication": {
            "type": [
                "object",
                "null"
            ],
            "description": "Plugins should restrict the API access: if an endpoint requires authentication, the user must provide one of the API keys e.g. in a request header",
            "default": null,
            "required": [
                "keys"
            ],
            "additionalProperties": false,
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "definitions": {
        "port": {
            "type": "number",
            "minimum": 0,
            "maximum": 65353
        },
        "smartContractConfig": {
            "type": "object",
            "required": [
                "contractAddress",
                "jsonRpcProvider"
            ],
            "additionalProperties": false,
            "properties": {
                "contractAddress": {
                    "type": "string",
                    "description": "Ethereum address of registry smart contract",
                    "pattern": "^0x[a-fA-F0-9]{40}$"
                },
                "jsonRpcProvider": {
                    "type": "string",
                    "description": "URL for JSON RPC Provider",
                    "format": "uri"
                }
            }
        }
    }
}

=== streamr-dev/network/packages/broker/configs/docker-3.env.json
{
    "$schema": "https://schema.streamr.network/config-v2.schema.json",
    "client": {
        "auth": {
            "privateKey": "0x2ba0e218041e81b8e5c88ee4134995c1e358c2c01664676d975792057c57e333"
        },
        "network": {
            "id": "0xde3331cA6B8B636E0b82Bf08E941F727B8927442",
            "trackers": {
                "contractAddress": "0xBFCF120a8fD17670536f1B27D9737B775b2FD4CF"
            },
            "location": {
                "latitude": 47.16,
                "longitude": 8.51,
                "country": "Switzerland",
                "city": "Zug"
            },
            "webrtcDisallowPrivateAddresses": false
        },
        "theGraphUrl": "http://10.200.10.1:8000/subgraphs/name/streamr-dev/network-contracts",
        "streamRegistryChainAddress": "0x6cCdd5d866ea766f6DF5965aA98DeCCD629ff222",
        "streamStorageRegistryChainAddress": "0xd04af489677001444280366Dd0885B03dAaDe71D",
        "storageNodeRegistryChainAddress": "0x231b810D98702782963472e1D60a25496999E75D",
        "streamRegistryChainRPCs": {
            "chainId": 8995,
            "rpcs": [
                {
                    "url": "http://10.200.10.1:8546"
                }
            ]
        },
        "mainChainRPCs": {
            "chainId": 8995,
            "rpcs": [
                {
                    "url": "http://10.200.10.1:8545"
                }
            ]
        },
        "maxRetries": 2
    },
    "httpServer": {
        "port": 8691
    },
    "apiAuthentication": null,
    "plugins": {
        "consoleMetrics": {
            "interval": 30
        },
        "info": {}
    }
}

=== streamr-dev/network/packages/broker/configs/development-1.env.json
{
    "$schema": "https://schema.streamr.network/config-v2.schema.json",
    "client": {
        "auth": {
            "privateKey": "0xaa7a3b3bb9b4a662e756e978ad8c6464412e7eef1b871f19e5120d4747bce966"
        },
        "network": {
            "id": "0xde1112f631486CfC759A50196853011528bC5FA0",
            "trackers": [
                {
                    "id": "0xb9e7cEBF7b03AE26458E32a059488386b05798e8",
                    "ws": "ws://127.0.0.1:30301",
                    "http": "http://127.0.0.1:30301"
                },
                {
                    "id": "0x0540A3e144cdD81F402e7772C76a5808B71d2d30",
                    "ws": "ws://127.0.0.1:30302",
                    "http": "http://127.0.0.1:30302"
                },
                {
                    "id": "0xf2C195bE194a2C91e93Eacb1d6d55a00552a85E2",
                    "ws": "ws://127.0.0.1:30303",
                    "http": "http://127.0.0.1:30303"
                }
            ],
            "location": {
                "latitude": 60.19,
                "longitude": 24.95,
                "country": "Finland",
                "city": "Helsinki"
            },
            "webrtcDisallowPrivateAddresses": false
        },
        "theGraphUrl": "http://10.200.10.1:8000/subgraphs/name/streamr-dev/network-contracts",
        "streamRegistryChainAddress": "0x6cCdd5d866ea766f6DF5965aA98DeCCD629ff222",
        "streamStorageRegistryChainAddress": "0xd04af489677001444280366Dd0885B03dAaDe71D",
        "storageNodeRegistryChainAddress": "0x231b810D98702782963472e1D60a25496999E75D",
        "streamRegistryChainRPCs": {
            "chainId": 8995,
            "rpcs": [
                {
                    "url": "http://10.200.10.1:8546"
                }
            ]
        },
        "mainChainRPCs": {
            "chainId": 8995,
            "rpcs": [
                {
                    "url": "http://10.200.10.1:8545"
                }
            ]
        },
        "maxRetries": 2
    },
    "httpServer": {
        "port": 8891
    },
    "apiAuthentication": null,
    "plugins": {
        "storage": {
            "cassandra": {
                "hosts": [
                    "127.0.0.1"
                ],
                "username": "",
                "password": "",
                "keyspace": "streamr_dev_v2",
                "datacenter": "datacenter1"
            },
            "storageConfig": {
                "refreshInterval": 10000
            }
        }
    }
}
